version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bank_app
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  java_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
